"use client";

import {
  Activity,
  Archive,
  BadgeCheck,
  Ban,
  Bandage,
  Banknote,
  Bed,
  Beer,
  Bell,
  Bone,
  Book,
  BookX,
  Briefcase,
  Bug,
  Building2,
  Cake,
  CakeSlice,
  Calendar,
  CalendarClock,
  CalendarX,
  Camera,
  Car,
  CarFront,
  Cat,
  ChefHat,
  Church,
  Circle,
  Clapperboard,
  Clock,
  CloudRain,
  Coffee,
  Cog,
  Contact,
  Cookie,
  Diamond,
  Dice5,
  Dice6,
  Dog,
  DoorClosed,
  DoorOpen,
  Drama,
  Droplet,
  Dumbbell,
  Eraser,
  Eye,
  EyeOff,
  FileBadge,
  FileLock,
  FileQuestion,
  FileSignature,
  FileText,
  FileX,
  Film,
  Fingerprint,
  Flag,
  Flame,
  Flower,
  Folder,
  FolderClock,
  FolderOpen,
  Footprints,
  Forward,
  Frame,
  Gauge,
  Gift,
  GitBranch,
  GitMerge,
  GraduationCap,
  Guitar,
  Hand,
  HandCoins,
  Handshake,
  Hash,
  Heart,
  HeartCrack,
  HeartHandshake,
  HeartOff,
  HeartPulse,
  HelpCircle,
  Hourglass,
  House,
  Image as ImageIcon,
  ImageOff,
  Key,
  KeyRound,
  Lamp,
  Landmark,
  Laptop,
  Laugh,
  ListOrdered,
  Lock,
  LogOut,
  Luggage,
  Mail,
  MailWarning,
  Mailbox,
  Map as MapIcon,
  MapPin,
  MessageCircle,
  MessageCircleWarning,
  MessageSquare,
  MessageSquareOff,
  MessageSquareWarning,
  MessagesSquare,
  Mic,
  MicOff,
  MicVocal,
  Moon,
  MoveDown,
  MoveVertical,
  Music,
  Newspaper,
  NotebookPen,
  Package,
  PartyPopper,
  Pause,
  PenLine,
  PenTool,
  Phone,
  PhoneCall,
  PhoneOff,
  Plane,
  PlaneLanding,
  Power,
  Presentation,
  Quote,
  Repeat,
  RotateCcw,
  RotateCw,
  Sailboat,
  Scale,
  School,
  Scissors,
  Scroll,
  ScrollText,
  Search,
  Send,
  Shield,
  ShieldAlert,
  ShieldOff,
  Shirt,
  ShoppingCart,
  ShowerHead,
  Siren,
  Smartphone,
  Sparkles,
  SpellCheck,
  Sprout,
  Star,
  Store,
  Swords,
  Table,
  Table2,
  Tag,
  Target,
  Tent,
  Thermometer,
  Ticket,
  Trees,
  TrendingUp,
  Trophy,
  Tv,
  User,
  UserCheck,
  UserMinus,
  UserRound,
  UserRoundX,
  UserX,
  Users,
  UsersRound,
  Utensils,
  VenetianMask,
  Video,
  Wallet,
  Wind,
  Wine,
  XCircle,
  type LucideIcon,
} from "lucide-react";

// Secret-bank image hints reference a bundled icon as "lucide:<kebab-name>".
// Only the names the seeded decks use are registered, so the icon set stays
// tree-shaken. Add new entries here when new decks introduce new icons.
const REGISTRY: Record<string, LucideIcon> = {
  "activity": Activity,
  "archive": Archive,
  "badge-check": BadgeCheck,
  "ban": Ban,
  "bandage": Bandage,
  "banknote": Banknote,
  "bed": Bed,
  "beer": Beer,
  "bell": Bell,
  "bone": Bone,
  "book": Book,
  "book-x": BookX,
  "briefcase": Briefcase,
  "bug": Bug,
  "building-2": Building2,
  "cake": Cake,
  "cake-slice": CakeSlice,
  "calendar": Calendar,
  "calendar-clock": CalendarClock,
  "calendar-x": CalendarX,
  "camera": Camera,
  "car": Car,
  "car-front": CarFront,
  "cat": Cat,
  "chef-hat": ChefHat,
  "church": Church,
  "circle": Circle,
  "clapperboard": Clapperboard,
  "clock": Clock,
  "cloud-rain": CloudRain,
  "coffee": Coffee,
  "cog": Cog,
  "contact": Contact,
  "cookie": Cookie,
  "diamond": Diamond,
  "dice-5": Dice5,
  "dice-6": Dice6,
  "dog": Dog,
  "door-closed": DoorClosed,
  "door-open": DoorOpen,
  "drama": Drama,
  "droplet": Droplet,
  "dumbbell": Dumbbell,
  "eraser": Eraser,
  "eye": Eye,
  "eye-off": EyeOff,
  "file-badge": FileBadge,
  "file-lock": FileLock,
  "file-question": FileQuestion,
  "file-signature": FileSignature,
  "file-text": FileText,
  "file-x": FileX,
  "film": Film,
  "fingerprint": Fingerprint,
  "flag": Flag,
  "flame": Flame,
  "flower": Flower,
  "folder": Folder,
  "folder-clock": FolderClock,
  "folder-open": FolderOpen,
  "footprints": Footprints,
  "forward": Forward,
  "frame": Frame,
  "gauge": Gauge,
  "gift": Gift,
  "git-branch": GitBranch,
  "git-merge": GitMerge,
  "graduation-cap": GraduationCap,
  "guitar": Guitar,
  "hand": Hand,
  "hand-coins": HandCoins,
  "handshake": Handshake,
  "hash": Hash,
  "heart": Heart,
  "heart-crack": HeartCrack,
  "heart-handshake": HeartHandshake,
  "heart-off": HeartOff,
  "heart-pulse": HeartPulse,
  "help-circle": HelpCircle,
  "hourglass": Hourglass,
  "house": House,
  "image": ImageIcon,
  "image-off": ImageOff,
  "key": Key,
  "key-round": KeyRound,
  "lamp": Lamp,
  "landmark": Landmark,
  "laptop": Laptop,
  "laugh": Laugh,
  "list-ordered": ListOrdered,
  "lock": Lock,
  "log-out": LogOut,
  "luggage": Luggage,
  "mail": Mail,
  "mail-warning": MailWarning,
  "mailbox": Mailbox,
  "map": MapIcon,
  "map-pin": MapPin,
  "message-circle": MessageCircle,
  "message-circle-warning": MessageCircleWarning,
  "message-square": MessageSquare,
  "message-square-off": MessageSquareOff,
  "message-square-warning": MessageSquareWarning,
  "messages-square": MessagesSquare,
  "mic": Mic,
  "mic-off": MicOff,
  "mic-vocal": MicVocal,
  "moon": Moon,
  "move-down": MoveDown,
  "move-vertical": MoveVertical,
  "music": Music,
  "newspaper": Newspaper,
  "notebook-pen": NotebookPen,
  "package": Package,
  "party-popper": PartyPopper,
  "pause": Pause,
  "pen-line": PenLine,
  "pen-tool": PenTool,
  "phone": Phone,
  "phone-call": PhoneCall,
  "phone-off": PhoneOff,
  "plane": Plane,
  "plane-landing": PlaneLanding,
  "power": Power,
  "presentation": Presentation,
  "quote": Quote,
  "repeat": Repeat,
  "rotate-ccw": RotateCcw,
  "rotate-cw": RotateCw,
  "sailboat": Sailboat,
  "scale": Scale,
  "school": School,
  "scissors": Scissors,
  "scroll": Scroll,
  "scroll-text": ScrollText,
  "search": Search,
  "send": Send,
  "shield": Shield,
  "shield-alert": ShieldAlert,
  "shield-off": ShieldOff,
  "shirt": Shirt,
  "shopping-cart": ShoppingCart,
  "shower-head": ShowerHead,
  "siren": Siren,
  "smartphone": Smartphone,
  "sparkles": Sparkles,
  "spell-check": SpellCheck,
  "sprout": Sprout,
  "star": Star,
  "store": Store,
  "swords": Swords,
  "table": Table,
  "table-2": Table2,
  "tag": Tag,
  "target": Target,
  "tent": Tent,
  "thermometer": Thermometer,
  "ticket": Ticket,
  "trees": Trees,
  "trending-up": TrendingUp,
  "trophy": Trophy,
  "tv": Tv,
  "user": User,
  "user-check": UserCheck,
  "user-minus": UserMinus,
  "user-round": UserRound,
  "user-round-x": UserRoundX,
  "user-x": UserX,
  "users": Users,
  "users-round": UsersRound,
  "utensils": Utensils,
  "venetian-mask": VenetianMask,
  "video": Video,
  "wallet": Wallet,
  "wind": Wind,
  "wine": Wine,
  "x-circle": XCircle,
};

/** Normalises a hint image_ref ("lucide:gift" | "gift") to a registered name, or null. */
export function hintIconName(ref: string | null | undefined): string | null {
  if (!ref) return null;
  const name = ref.startsWith("lucide:") ? ref.slice(7) : ref;
  return name in REGISTRY ? name : null;
}

/** True when this hint should render as a bundled icon rather than a stored image. */
export function isIconHint(
  hint: { image_ref?: string | null; asset_path?: string | null } | null | undefined,
): boolean {
  return !!hint && !!hint.image_ref && !hint.asset_path && hintIconName(hint.image_ref) != null;
}

export function HintIcon({ refValue, className }: { refValue: string | null | undefined; className?: string }) {
  const name = hintIconName(refValue);
  const Icon = name ? REGISTRY[name] : HelpCircle;
  return (
    <div className={className ?? "flex items-center justify-center rounded-xl bg-white/60 py-8"}>
      <Icon className="h-16 w-16 text-[var(--muted)]" strokeWidth={1.5} aria-hidden />
    </div>
  );
}
