-- Second pass on public.secret_bank (item 21). Re-curated toward secrets that
-- actually work in the game: one concrete claim, guessable from 10 hints
-- (image / text / emoji), with a definite reveal. Fewer everyday "quirk"
-- confessions, more facts, life events and big-swing bluffs. ~400 bilingual
-- entries across the same 10 packs, bringing the bank to ~600 total. Idempotent
-- (on conflict do nothing) — note this file is already applied to prod, so a
-- fresh seed migration is needed for existing databases to pick up the changes.

insert into public.secret_bank (category, locale, text) values
-- family (en)
('family','en','I found out as an adult that I have a half-sibling.'),
('family','en','My grandparents were second cousins.'),
('family','en','I was named after my dad''s ex.'),
('family','en','I broke a family heirloom and blamed the dog for nine years.'),
('family','en','I know which relative is not biologically related, and I have never said.'),
('family','en','My parents eloped and told everyone the wedding photos were lost.'),
('family','en','I was conceived on a trip my parents still swear they took separately.'),
('family','en','There is a family recipe I have and will take to my grave.'),
('family','en','I opened a relative''s mail for a year to hide a debt letter.'),
('family','en','My family thinks I finished a degree that I did not.'),
('family','en','I have a cousin I first met at a funeral in my thirties.'),
('family','en','My middle name is a typo on my birth certificate that stuck.'),
('family','en','I gave away a family ring and said it was stolen.'),
('family','en','I found my adoption papers before anyone planned to tell me.'),
('family','en','My parents met while one of them was engaged to someone else.'),
('family','en','I have quietly paid a relative''s rent for two years.'),
('family','en','A "family friend" at every holiday is actually my parent''s ex.'),
('family','en','I lost the deed to a family plot and never admitted it.'),
('family','en','My grandfather had a whole first family we only learned about later.'),
('family','en','I forged a parent''s signature on school reports for three years.'),
-- family (fr)
('family','fr','J''ai appris adulte que j''ai un demi-frère ou une demi-sœur.'),
('family','fr','Mes grands-parents étaient cousins au second degré.'),
('family','fr','On m''a donné le prénom de l''ex de mon père.'),
('family','fr','J''ai cassé un objet de famille et accusé le chien pendant neuf ans.'),
('family','fr','Je sais quel proche n''a aucun lien de sang avec nous et je ne l''ai jamais dit.'),
('family','fr','Mes parents se sont mariés en cachette et ont dit que les photos étaient perdues.'),
('family','fr','J''ai été conçu pendant un voyage que mes parents jurent avoir fait séparément.'),
('family','fr','Il y a une recette de famille que je détiens et que j''emporterai dans la tombe.'),
('family','fr','J''ai ouvert le courrier d''un proche pendant un an pour cacher une lettre de dettes.'),
('family','fr','Ma famille croit que j''ai terminé un diplôme que je n''ai pas.'),
('family','fr','J''ai un cousin que je n''ai rencontré qu''à un enterrement, la trentaine passée.'),
('family','fr','Mon deuxième prénom est une faute sur mon acte de naissance qui est restée.'),
('family','fr','J''ai donné une bague de famille et dit qu''on me l''avait volée.'),
('family','fr','J''ai trouvé mes papiers d''adoption avant qu''on prévoie de me le dire.'),
('family','fr','Mes parents se sont rencontrés alors que l''un était fiancé à quelqu''un d''autre.'),
('family','fr','Je paie discrètement le loyer d''un proche depuis deux ans.'),
('family','fr','Un « ami de la famille » présent à chaque fête est en fait l''ex d''un de mes parents.'),
('family','fr','J''ai perdu l''acte de propriété d''un terrain familial et je ne l''ai jamais avoué.'),
('family','fr','Mon grand-père avait toute une première famille dont on n''a appris l''existence que plus tard.'),
('family','fr','J''ai imité la signature d''un parent sur mes bulletins pendant trois ans.'),

-- kids (en)
('kids','en','I was in a TV advert as a baby.'),
('kids','en','I won a national competition as a kid and still have the trophy.'),
('kids','en','I broke my arm falling off a stage in a school play.'),
('kids','en','I was expelled from primary school and my parents said we moved.'),
('kids','en','I still have a baby tooth in a drawer thirty years on.'),
('kids','en','I once got lost on a school trip for four hours.'),
('kids','en','I believed I was adopted until I was seventeen.'),
('kids','en','I set off the school fire alarm and never got caught.'),
('kids','en','I was the voice of something you have heard.'),
('kids','en','I failed the same school year twice.'),
('kids','en','I ran away from home at nine and got two streets away.'),
('kids','en','I met a world leader on a school trip and have the photo.'),
('kids','en','I was a catalogue model as a child and nobody remembers.'),
('kids','en','I stole from a classmate at seven and still feel it.'),
('kids','en','I was homeschooled for a year for a reason I have never explained.'),
('kids','en','I won the school spelling bee by guessing the last word.'),
('kids','en','I broke a bone doing something I had been told not to do.'),
('kids','en','I had a pen pal for ten years and then we finally met.'),
('kids','en','I was suspended for something I did not do and let it stand.'),
('kids','en','My first word was a brand name.'),
-- kids (fr)
('kids','fr','J''ai tourné dans une pub télé quand j''étais bébé.'),
('kids','fr','J''ai gagné un concours national enfant et j''ai encore le trophée.'),
('kids','fr','Je me suis cassé le bras en tombant d''une scène pendant un spectacle scolaire.'),
('kids','fr','J''ai été renvoyé de l''école primaire et mes parents ont dit qu''on avait déménagé.'),
('kids','fr','J''ai encore une dent de lait dans un tiroir, trente ans plus tard.'),
('kids','fr','Je me suis perdu quatre heures pendant une sortie scolaire.'),
('kids','fr','J''ai cru que j''étais adopté jusqu''à mes dix-sept ans.'),
('kids','fr','J''ai déclenché l''alarme incendie de l''école et on ne m''a jamais attrapé.'),
('kids','fr','J''ai prêté ma voix à quelque chose que tu as déjà entendu.'),
('kids','fr','J''ai redoublé deux fois la même année.'),
('kids','fr','J''ai fait une fugue à neuf ans et je suis allé à deux rues de là.'),
('kids','fr','J''ai rencontré un chef d''État lors d''une sortie scolaire et j''ai la photo.'),
('kids','fr','J''ai été mannequin enfant pour un catalogue dont personne ne se souvient.'),
('kids','fr','J''ai volé un camarade en CE2 et ça me reste encore.'),
('kids','fr','J''ai été scolarisé à la maison un an pour une raison que je n''ai jamais expliquée.'),
('kids','fr','J''ai gagné le concours d''orthographe de l''école en devinant le dernier mot.'),
('kids','fr','Je me suis cassé un os en faisant un truc qu''on m''avait interdit.'),
('kids','fr','J''ai eu un correspondant pendant dix ans et on a fini par se rencontrer.'),
('kids','fr','J''ai été exclu pour un truc que je n''avais pas fait et j''ai laissé faire.'),
('kids','fr','Mon premier mot était une marque.'),

-- couples (en)
('couples','en','I dated two people with the same first name back to back and corrected neither.'),
('couples','en','I met my partner at their leaving party for a job I then got.'),
('couples','en','I have been engaged before and almost nobody here knows.'),
('couples','en','I proposed twice to the same person.'),
('couples','en','I found my partner on an app I joined to check on an ex.'),
('couples','en','I kept my ex''s hoodie through my next two relationships.'),
('couples','en','I once went on two dates in one night.'),
('couples','en','I said "I love you" first and then panicked for a week.'),
('couples','en','My partner and I split for a year and called it a "break".'),
('couples','en','I matched with a relative on a dating app.'),
('couples','en','I planned a proposal, lost my nerve, and ate the ring cost.'),
('couples','en','I have been someone''s rebound and knew it going in.'),
('couples','en','My first kiss was with someone I later worked for.'),
('couples','en','I moved cities for a relationship that ended in a month.'),
('couples','en','I wrote my wedding speech before we were engaged.'),
('couples','en','I dated a friend''s ex and we still have not told them.'),
('couples','en','I got back with an ex out of boredom and it lasted two years.'),
('couples','en','I met my partner''s parents before my partner thought we were serious.'),
('couples','en','I have a marriage on paper that our families never knew about.'),
('couples','en','I once left a date through the bathroom window.'),
-- couples (fr)
('couples','fr','J''ai fréquenté deux personnes du même prénom coup sur coup sans jamais rectifier.'),
('couples','fr','J''ai rencontré mon/ma partenaire à son pot de départ, pour un poste que j''ai eu ensuite.'),
('couples','fr','J''ai déjà été fiancé, et presque personne ici ne le sait.'),
('couples','fr','J''ai demandé deux fois la même personne en mariage.'),
('couples','fr','J''ai trouvé mon/ma partenaire sur une appli installée pour surveiller un ex.'),
('couples','fr','J''ai gardé le sweat de mon ex pendant mes deux relations suivantes.'),
('couples','fr','J''ai déjà enchaîné deux rendez-vous dans la même soirée.'),
('couples','fr','J''ai dit « je t''aime » en premier puis j''ai paniqué pendant une semaine.'),
('couples','fr','Mon/ma partenaire et moi avons rompu un an en appelant ça une « pause ».'),
('couples','fr','J''ai matché avec un membre de ma famille sur une appli de rencontres.'),
('couples','fr','J''ai préparé une demande en mariage, pris peur, et perdu le prix de la bague.'),
('couples','fr','J''ai déjà été le rebond de quelqu''un et je le savais dès le départ.'),
('couples','fr','Mon premier baiser était avec une personne pour qui j''ai travaillé plus tard.'),
('couples','fr','J''ai changé de ville pour une relation qui a duré un mois.'),
('couples','fr','J''ai écrit mon discours de mariage avant même les fiançailles.'),
('couples','fr','J''ai fréquenté l''ex d''un ami et on ne le lui a toujours pas dit.'),
('couples','fr','Je me suis remis avec un ex par ennui et ça a duré deux ans.'),
('couples','fr','J''ai rencontré les parents de mon/ma partenaire avant qu''il nous croie sérieux.'),
('couples','fr','J''ai un mariage sur papier que nos familles n''ont jamais connu.'),
('couples','fr','Je suis déjà sorti d''un rendez-vous par la fenêtre des toilettes.'),

-- girls_night (en)
('girls_night','en','I have been in a music video.'),
('girls_night','en','I got escorted out of a club and told everyone I left early.'),
('girls_night','en','I kissed someone famous and have the blurry photo.'),
('girls_night','en','I have a tattoo nobody in this room has seen.'),
('girls_night','en','I was a bridesmaid for someone I no longer speak to.'),
('girls_night','en','A stranger threw a drink on me and it made the local paper.'),
('girls_night','en','I have flown somewhere for one night and flown straight back.'),
('girls_night','en','I sat a phone interview as my friend and she got the job.'),
('girls_night','en','I was dumped by text on my birthday.'),
('girls_night','en','I ran a fake account about someone for a month.'),
('girls_night','en','I have sung on a stage in front of strangers, sober.'),
('girls_night','en','I framed a nightclub photo as a joke and it is still up.'),
('girls_night','en','I left the country the day after a breakup with no plan.'),
('girls_night','en','I have been to a wedding I was not invited to.'),
('girls_night','en','I dated someone for three months without learning their surname.'),
('girls_night','en','I cried in a work bathroom and blamed hay fever in December.'),
('girls_night','en','I am in the background of a film you have seen.'),
('girls_night','en','I once returned a dress after wearing it to an event.'),
('girls_night','en','I keep a second phone number only for dates.'),
('girls_night','en','I met my closest friend in a bar toilet queue.'),
-- girls_night (fr)
('girls_night','fr','J''ai déjà tourné dans un clip.'),
('girls_night','fr','Je me suis fait sortir d''une boîte et j''ai fait passer ça pour un départ anticipé.'),
('girls_night','fr','J''ai embrassé une personne célèbre et j''ai la photo floue.'),
('girls_night','fr','J''ai un tatouage que personne dans cette pièce n''a vu.'),
('girls_night','fr','J''ai été demoiselle d''honneur pour quelqu''un à qui je ne parle plus.'),
('girls_night','fr','Une inconnue m''a renversé un verre dessus et c''est passé dans le journal local.'),
('girls_night','fr','J''ai déjà pris l''avion pour une seule nuit et je suis rentrée aussitôt.'),
('girls_night','fr','J''ai passé un entretien téléphonique à la place de mon amie et elle a eu le poste.'),
('girls_night','fr','On m''a larguée par message le jour de mon anniversaire.'),
('girls_night','fr','J''ai tenu un faux compte sur quelqu''un pendant un mois.'),
('girls_night','fr','J''ai chanté sur une scène devant des inconnus, à jeun.'),
('girls_night','fr','J''ai fait encadrer une photo de boîte de nuit pour rire et c''est toujours accroché.'),
('girls_night','fr','J''ai quitté le pays le lendemain d''une rupture, sans aucun plan.'),
('girls_night','fr','Je suis allée à un mariage où je n''étais pas invitée.'),
('girls_night','fr','J''ai fréquenté quelqu''un trois mois sans jamais connaître son nom de famille.'),
('girls_night','fr','J''ai pleuré dans les toilettes du travail et blâmé le rhume des foins en décembre.'),
('girls_night','fr','On me voit à l''arrière-plan d''un film que tu as vu.'),
('girls_night','fr','J''ai déjà rendu une robe après l''avoir portée à un événement.'),
('girls_night','fr','J''ai un numéro secondaire que je ne donne qu''aux rendez-vous.'),
('girls_night','fr','J''ai rencontré ma meilleure amie dans la file des toilettes d''un bar.'),

-- guys_night (en)
('guys_night','en','I have been arrested.'),
('guys_night','en','I failed my driving test five times.'),
('guys_night','en','I wrote off a car showing off in an empty car park.'),
('guys_night','en','I have a scar I tell three different stories about.'),
('guys_night','en','I lost a month''s rent on a single bet.'),
('guys_night','en','I got a tattoo abroad and cannot read what it says.'),
('guys_night','en','I started a bar fight by accident.'),
('guys_night','en','I drove four hours to a gig and forgot the tickets.'),
('guys_night','en','I have thrown up on someone famous.'),
('guys_night','en','I was barred from a pub I still walk past.'),
('guys_night','en','I broke a bone on a trampoline at twenty-nine.'),
('guys_night','en','I got on the wrong flight and only noticed on landing.'),
('guys_night','en','I have a criminal record for something very stupid at nineteen.'),
('guys_night','en','I pretended I could sail and nearly capsized the boat.'),
('guys_night','en','I sold my car to a friend without mentioning the gearbox.'),
('guys_night','en','I have been escorted off a golf course.'),
('guys_night','en','I won a pub quiz by cheating and kept the trophy.'),
('guys_night','en','I did a bungee jump and cried the whole way down.'),
('guys_night','en','I went to a festival and saw not one band.'),
('guys_night','en','I got a speeding ticket on the way to a driving lesson.'),
-- guys_night (fr)
('guys_night','fr','J''ai déjà été arrêté par la police.'),
('guys_night','fr','J''ai raté mon permis cinq fois.'),
('guys_night','fr','J''ai bousillé une voiture en frimant sur un parking vide.'),
('guys_night','fr','J''ai une cicatrice sur laquelle je raconte trois histoires différentes.'),
('guys_night','fr','J''ai perdu un mois de loyer sur un seul pari.'),
('guys_night','fr','Je me suis fait tatouer à l''étranger et je ne sais pas lire ce que ça dit.'),
('guys_night','fr','J''ai déclenché une bagarre de bar sans le vouloir.'),
('guys_night','fr','J''ai roulé quatre heures pour un concert en oubliant les billets.'),
('guys_night','fr','J''ai vomi sur quelqu''un de célèbre.'),
('guys_night','fr','J''ai été banni d''un bar devant lequel je passe encore.'),
('guys_night','fr','Je me suis cassé un os sur un trampoline à vingt-neuf ans.'),
('guys_night','fr','J''ai pris le mauvais avion et je ne l''ai vu qu''à l''atterrissage.'),
('guys_night','fr','J''ai un casier pour une bêtise à dix-neuf ans.'),
('guys_night','fr','J''ai fait semblant de savoir naviguer et on a failli chavirer.'),
('guys_night','fr','J''ai vendu ma voiture à un ami sans parler de la boîte de vitesses.'),
('guys_night','fr','Je me suis fait escorter hors d''un parcours de golf.'),
('guys_night','fr','J''ai gagné un quiz de bar en trichant et j''ai gardé le trophée.'),
('guys_night','fr','J''ai fait un saut à l''élastique en pleurant toute la descente.'),
('guys_night','fr','Je suis allé à un festival sans voir un seul groupe.'),
('guys_night','fr','J''ai eu une amende pour excès de vitesse en allant à une leçon de conduite.'),

-- work_party (en)
('work_party','en','I got the job by lying about knowing Excel.'),
('work_party','en','I once replied all to the entire company by accident.'),
('work_party','en','I have dated someone I directly managed.'),
('work_party','en','I quit a job by simply never going back.'),
('work_party','en','I forwarded a complaint about my boss to my boss.'),
('work_party','en','I was promoted for a project that was mostly someone else''s.'),
('work_party','en','I have cried in a stairwell and walked back in smiling.'),
('work_party','en','I learned I was the lowest paid on the team and said nothing for a year.'),
('work_party','en','I slept through a client presentation I was leading.'),
('work_party','en','I put a fake reference on my CV and no one ever called it.'),
('work_party','en','I was fired on my first day.'),
('work_party','en','I have interviewed at a competitor on my lunch break.'),
('work_party','en','I sent a screenshot of a chat to the person in the chat.'),
('work_party','en','I took credit for fixing a bug I had caused.'),
('work_party','en','I have a work nemesis who has no idea.'),
('work_party','en','I was walked out by security after resigning.'),
('work_party','en','I ran a meeting about a document I had not read.'),
('work_party','en','I have been paid to leave a job quietly.'),
('work_party','en','I applied for my manager''s role without telling them.'),
('work_party','en','I met my partner at a work party and we hid it for a year.'),
-- work_party (fr)
('work_party','fr','J''ai eu le poste en mentant sur mon niveau d''Excel.'),
('work_party','fr','J''ai déjà répondu « à tous » à toute l''entreprise par erreur.'),
('work_party','fr','J''ai déjà fréquenté une personne que je dirigeais directement.'),
('work_party','fr','J''ai quitté un job en n''y retournant simplement jamais.'),
('work_party','fr','J''ai transféré à mon chef une plainte qui le visait.'),
('work_party','fr','J''ai été promu pour un projet qui était surtout celui de quelqu''un d''autre.'),
('work_party','fr','J''ai pleuré dans une cage d''escalier et je suis revenu en souriant.'),
('work_party','fr','J''ai découvert que j''étais le moins payé de l''équipe et je n''ai rien dit pendant un an.'),
('work_party','fr','J''ai dormi pendant une présentation client que je dirigeais.'),
('work_party','fr','J''ai mis une fausse référence sur mon CV et personne n''a jamais appelé.'),
('work_party','fr','J''ai été viré le premier jour.'),
('work_party','fr','J''ai passé un entretien chez un concurrent pendant ma pause déjeuner.'),
('work_party','fr','J''ai envoyé la capture d''une conversation à la personne concernée.'),
('work_party','fr','Je me suis attribué la correction d''un bug que j''avais causé.'),
('work_party','fr','J''ai un ennemi juré au travail qui n''en a aucune idée.'),
('work_party','fr','Je me suis fait raccompagner par la sécurité après ma démission.'),
('work_party','fr','J''ai animé une réunion sur un document que je n''avais pas lu.'),
('work_party','fr','On m''a payé pour quitter un poste discrètement.'),
('work_party','fr','J''ai postulé au poste de mon manager sans le lui dire.'),
('work_party','fr','J''ai rencontré mon/ma partenaire à une fête du bureau et on l''a caché un an.'),

-- awkward (en)
('awkward','en','I called my boss "Mum" in a meeting and just kept talking.'),
('awkward','en','I introduced my partner as my sibling on a work call.'),
('awkward','en','I clapped alone at a funeral by reflex.'),
('awkward','en','I waved back at someone for a full minute who was not waving at me.'),
('awkward','en','I sent a screenshot of a person to that exact person.'),
('awkward','en','I congratulated a stranger on a pregnancy that was not one.'),
('awkward','en','I gave a best-man speech and blanked on the groom''s name.'),
('awkward','en','I liked a photo from 2014 while deep in someone''s profile.'),
('awkward','en','I walked into a glass door at a job interview and still got hired.'),
('awkward','en','I texted my crush a message meant for my mum.'),
('awkward','en','I said "love you" to a client as I hung up.'),
('awkward','en','I turned up in costume to a party that was not fancy dress.'),
('awkward','en','I called my teacher by the wrong first name in front of the class.'),
('awkward','en','I RSVP''d yes to a wedding and turned up the wrong weekend.'),
('awkward','en','I gave a toast at the wrong table at a stranger''s wedding.'),
('awkward','en','I replied to a group email with something meant for one person.'),
('awkward','en','I got a colleague''s name wrong for two years before anyone said.'),
('awkward','en','I fell asleep in a meeting and woke myself up talking.'),
('awkward','en','I hugged someone going for a handshake at my own leaving do.'),
('awkward','en','I loudly sang "happy birthday" to the wrong person at the table.'),
-- awkward (fr)
('awkward','fr','J''ai appelé mon chef « maman » en réunion et j''ai continué à parler.'),
('awkward','fr','J''ai présenté mon/ma partenaire comme mon frère ou ma sœur en visio pro.'),
('awkward','fr','J''ai applaudi tout seul à un enterrement, par réflexe.'),
('awkward','fr','J''ai fait signe une minute entière à quelqu''un qui ne me saluait pas.'),
('awkward','fr','J''ai envoyé la capture d''une personne à cette personne exactement.'),
('awkward','fr','J''ai félicité une inconnue pour une grossesse qui n''en était pas une.'),
('awkward','fr','J''ai fait un discours de témoin en oubliant le prénom du marié.'),
('awkward','fr','J''ai liké une photo de 2014 en pleine exploration d''un profil.'),
('awkward','fr','Je me suis pris une porte vitrée à un entretien et j''ai quand même été embauché.'),
('awkward','fr','J''ai envoyé à mon crush un message destiné à ma mère.'),
('awkward','fr','J''ai dit « je t''aime » à un client en raccrochant.'),
('awkward','fr','Je suis venu déguisé à une soirée qui n''était pas costumée.'),
('awkward','fr','J''ai appelé mon prof par le mauvais prénom devant toute la classe.'),
('awkward','fr','J''ai confirmé pour un mariage et je me suis présenté le mauvais week-end.'),
('awkward','fr','J''ai porté un toast à la mauvaise table au mariage d''un inconnu.'),
('awkward','fr','J''ai répondu à un mail groupé avec un message destiné à une seule personne.'),
('awkward','fr','Je me suis trompé de prénom sur un collègue pendant deux ans avant qu''on me corrige.'),
('awkward','fr','Je me suis endormi en réunion et je me suis réveillé en parlant.'),
('awkward','fr','J''ai enlacé quelqu''un qui me tendait la main, à mon propre pot de départ.'),
('awkward','fr','J''ai chanté « joyeux anniversaire » très fort à la mauvaise personne à table.'),

-- wholesome (en)
('wholesome','en','I gave a stranger my coat, never got it back, and do not mind.'),
('wholesome','en','I donated bone marrow to someone I have never met.'),
('wholesome','en','I have been a friend''s emergency contact for ten years and never told my family.'),
('wholesome','en','I paid off a stranger''s layaway one Christmas.'),
('wholesome','en','I taught my grandmother to send her first email.'),
('wholesome','en','I got two friends talking again after twenty years of silence.'),
('wholesome','en','I have written to a sponsored child every month for eight years.'),
('wholesome','en','I gave blood every time I was allowed for a decade.'),
('wholesome','en','I once talked someone through a bad night on a bridge.'),
('wholesome','en','I kept a promise to a dying friend that took five years.'),
('wholesome','en','I secretly paid for a coworker''s course and never said.'),
('wholesome','en','I still call my primary school teacher on her birthday.'),
('wholesome','en','I adopted the oldest dog in the shelter on purpose.'),
('wholesome','en','I found a wallet with a lot of cash and returned all of it.'),
('wholesome','en','I named my child after the nurse who saved them.'),
('wholesome','en','I have been a prison pen pal for three years.'),
('wholesome','en','I gave my bonus to the person laid off instead of me.'),
('wholesome','en','I drove six hours to sit with a friend for one afternoon.'),
('wholesome','en','I learned sign language for one person at my office.'),
('wholesome','en','I plant a tree for every person I have lost.'),
-- wholesome (fr)
('wholesome','fr','J''ai donné mon manteau à un inconnu, je ne l''ai jamais revu et ça ne me dérange pas.'),
('wholesome','fr','J''ai donné ma moelle osseuse à quelqu''un que je n''ai jamais rencontré.'),
('wholesome','fr','Je suis le contact d''urgence d''un ami depuis dix ans et ma famille l''ignore.'),
('wholesome','fr','Une année, j''ai réglé la commande en attente d''un inconnu à Noël.'),
('wholesome','fr','J''ai appris à ma grand-mère à envoyer son premier courriel.'),
('wholesome','fr','J''ai remis deux amis en contact après vingt ans de silence.'),
('wholesome','fr','J''écris à un enfant parrainé chaque mois depuis huit ans.'),
('wholesome','fr','J''ai donné mon sang à chaque fois que c''était permis pendant dix ans.'),
('wholesome','fr','J''ai déjà accompagné quelqu''un au téléphone pendant une mauvaise nuit sur un pont.'),
('wholesome','fr','J''ai tenu une promesse faite à un ami mourant, ça m''a pris cinq ans.'),
('wholesome','fr','J''ai financé en secret la formation d''un collègue et je ne l''ai jamais dit.'),
('wholesome','fr','J''appelle encore ma maîtresse d''école primaire le jour de son anniversaire.'),
('wholesome','fr','J''ai adopté exprès le chien le plus vieux du refuge.'),
('wholesome','fr','J''ai trouvé un portefeuille avec beaucoup d''argent et j''ai tout rendu.'),
('wholesome','fr','J''ai donné à mon enfant le prénom de l''infirmière qui l''a sauvé.'),
('wholesome','fr','Je corresponds avec un détenu depuis trois ans.'),
('wholesome','fr','J''ai donné ma prime à la personne licenciée à ma place.'),
('wholesome','fr','J''ai roulé six heures pour passer un après-midi avec un ami.'),
('wholesome','fr','J''ai appris la langue des signes pour une seule personne au bureau.'),
('wholesome','fr','Je plante un arbre pour chaque personne que j''ai perdue.'),

-- dark (en)
('dark','en','I let a friend take the blame for something I broke at their party.'),
('dark','en','I read a message meant for someone else and used what I learned.'),
('dark','en','I skipped a funeral I should have gone to and lied about why.'),
('dark','en','I ended a ten-year friendship over one text and never explained.'),
('dark','en','I know a secret about a relative and I am holding it for leverage.'),
('dark','en','I once let someone get fired to protect myself.'),
('dark','en','I screenshotted a friend''s confession and showed it to two people.'),
('dark','en','I skipped a wedding and posted "in bed with flu" from a bar.'),
('dark','en','I told a partner''s secret to win an argument with someone else.'),
('dark','en','I kept a spare key I was asked to give back.'),
('dark','en','I let a couple break up over a rumour I could have corrected.'),
('dark','en','I felt relief at news I was meant to be sad about.'),
('dark','en','I have not spoken to a sibling in three years and tell people we are "just busy".'),
('dark','en','I gave a bad reference on purpose and it worked.'),
('dark','en','I found money a friend lost on a night out and never told them.'),
('dark','en','I ghosted someone the day after they helped me move.'),
('dark','en','I let my parents believe the version of a story where they are the problem.'),
('dark','en','I have wished a rival''s big day would go quietly wrong.'),
('dark','en','I took something from a house I was a guest in.'),
('dark','en','I stayed friends with someone only to keep an eye on them.'),
-- dark (fr)
('dark','fr','J''ai laissé un ami porter le blâme d''un truc que j''avais cassé chez lui, à sa fête.'),
('dark','fr','J''ai lu un message destiné à quelqu''un d''autre et je m''en suis servi.'),
('dark','fr','J''ai séché un enterrement où j''aurais dû être et j''ai menti sur la raison.'),
('dark','fr','J''ai mis fin à une amitié de dix ans sur un seul message, sans jamais m''expliquer.'),
('dark','fr','Je détiens un secret sur un proche et je le garde comme moyen de pression.'),
('dark','fr','J''ai déjà laissé quelqu''un se faire virer pour me protéger.'),
('dark','fr','J''ai fait une capture de la confession d''un ami et je l''ai montrée à deux personnes.'),
('dark','fr','J''ai séché un mariage en postant « au lit avec la grippe » depuis un bar.'),
('dark','fr','J''ai révélé le secret d''un/e partenaire pour gagner une dispute avec quelqu''un d''autre.'),
('dark','fr','J''ai gardé un double de clé qu''on m''avait demandé de rendre.'),
('dark','fr','J''ai laissé un couple rompre sur une rumeur que j''aurais pu démentir.'),
('dark','fr','J''ai ressenti du soulagement à une nouvelle censée me rendre triste.'),
('dark','fr','Je ne parle plus à un frère ou une sœur depuis trois ans et je dis qu''on est « juste occupés ».'),
('dark','fr','J''ai donné une mauvaise référence exprès et ça a marché.'),
('dark','fr','J''ai trouvé l''argent qu''un ami avait perdu en soirée et je ne lui ai jamais dit.'),
('dark','fr','J''ai ghosté quelqu''un le lendemain du jour où il m''a aidé à déménager.'),
('dark','fr','Je laisse mes parents croire la version d''une histoire où ce sont eux le problème.'),
('dark','fr','J''ai souhaité que le grand jour d''un rival tourne discrètement mal.'),
('dark','fr','J''ai pris quelque chose dans une maison où j''étais invité.'),
('dark','fr','Je suis resté ami avec quelqu''un uniquement pour le surveiller.'),

-- spicy (en)
('spicy','en','I slept with a teacher.'),
('spicy','en','There is a number in my phone saved as a takeaway that is a person.'),
('spicy','en','I hooked up with someone at a wedding and left before the cake.'),
('spicy','en','I dated two people who knew each other and neither knew about me.'),
('spicy','en','I met a partner on an app I joined while still with someone else.'),
('spicy','en','I have sent a very spicy text to entirely the wrong person.'),
('spicy','en','I hooked up with a friend''s sibling and we never told them.'),
('spicy','en','I left a party early to see someone I swore I was over.'),
('spicy','en','I once went home with someone whose name I never learned.'),
('spicy','en','I faked it for an entire relationship.'),
('spicy','en','I kissed someone at their own engagement party.'),
('spicy','en','I was the other person and did not find out until later.'),
('spicy','en','I matched with my boss on an app and we both swiped away fast.'),
('spicy','en','I slept with an ex the night before their wedding, not to me.'),
('spicy','en','I have kept a pair of someone''s underwear as a trophy.'),
('spicy','en','My "gym friend" is someone I have never done a workout with.'),
('spicy','en','I lost my virginity somewhere I could have been arrested.'),
('spicy','en','I dated someone purely because of who it would annoy.'),
('spicy','en','I got caught by a flatmate and we never spoke of it.'),
('spicy','en','I have a tattoo in a place only two people have seen.'),
-- spicy (fr)
('spicy','fr','J''ai couché avec un prof.'),
('spicy','fr','Il y a un numéro dans mon téléphone enregistré comme un resto à emporter et c''est une personne.'),
('spicy','fr','J''ai eu une aventure à un mariage et je suis parti avant le gâteau.'),
('spicy','fr','J''ai fréquenté deux personnes qui se connaissaient et aucune ne savait pour moi.'),
('spicy','fr','J''ai rencontré un/e partenaire sur une appli installée alors que j''étais encore avec quelqu''un.'),
('spicy','fr','J''ai envoyé un message très chaud à la mauvaise personne.'),
('spicy','fr','J''ai eu une aventure avec le frère ou la sœur d''un ami et on ne lui a jamais dit.'),
('spicy','fr','Je suis parti d''une fête tôt pour voir quelqu''un dont je jurais être passé à autre chose.'),
('spicy','fr','Je suis déjà rentré avec quelqu''un dont je n''ai jamais su le prénom.'),
('spicy','fr','J''ai simulé pendant toute une relation.'),
('spicy','fr','J''ai embrassé quelqu''un à ses propres fiançailles.'),
('spicy','fr','J''ai été l''amant ou l''amante sans le savoir jusqu''à plus tard.'),
('spicy','fr','J''ai matché avec mon chef sur une appli et on a swipé très vite.'),
('spicy','fr','J''ai couché avec un ex la veille de son mariage — pas avec moi.'),
('spicy','fr','J''ai gardé un sous-vêtement de quelqu''un comme trophée.'),
('spicy','fr','Mon ou ma « pote de sport » est quelqu''un avec qui je n''ai jamais fait de sport.'),
('spicy','fr','J''ai perdu ma virginité dans un lieu où ça pouvait me valoir une arrestation.'),
('spicy','fr','J''ai fréquenté quelqu''un uniquement pour qui ça allait agacer.'),
('spicy','fr','Je me suis fait surprendre par un coloc et on n''en a jamais reparlé.'),
('spicy','fr','J''ai un tatouage à un endroit que seules deux personnes ont vu.')
on conflict do nothing;
