-- Second pass on public.secret_bank (item 21). ~400 more curated bilingual
-- entries, bringing the bank to ~600 total across the same 10 packs — inside
-- the agreed "curated ~600-800" band. Idempotent (on conflict do nothing).

insert into public.secret_bank (category, locale, text) values
-- family (en)
('family','en','I have a group chat with my siblings that my parents will never see.'),
('family','en','I still have a piggy bank and I check it more than my actual savings.'),
('family','en','I once told a relative their haircut looked great and it did not.'),
('family','en','I have hidden in a bathroom to get a break at a family gathering.'),
('family','en','I keep score of who calls me first, and I have never told anyone.'),
('family','en','I let a family myth about me continue because it is more flattering than the truth.'),
('family','en','I have a "good" set of dishes I have never once used.'),
('family','en','I recycled a school project and handed it in twice, years apart.'),
('family','en','I have googled how to get a stain out of a relative''s carpet in a panic.'),
('family','en','I pretend my phone died to end long family calls.'),
('family','en','I have a favourite niece or nephew and I bring them the better gift.'),
('family','en','I still ask a parent to book my dentist appointments.'),
('family','en','I once ate the last of something and blamed a sibling who was not even home.'),
('family','en','I have a drawer of cables and I do not know what a single one is for.'),
('family','en','I have skipped a relative''s call three times in a row and then texted "sorry, busy!".'),
('family','en','I know exactly which floorboard creaks and I plan my late nights around it.'),
('family','en','I have kept a library book from my childhood town on purpose.'),
('family','en','I told everyone I cooked the dinner. The oven did most of it.'),
('family','en','I have a spare charger hidden so nobody else in the house can take it.'),
('family','en','I remember a grudge from a board game in 2009 and I am not letting it go.'),
-- family (fr)
('family','fr','J''ai une conversation de groupe avec mes frères et sœurs que mes parents ne verront jamais.'),
('family','fr','J''ai encore une tirelire et je la vérifie plus souvent que mon vrai compte.'),
('family','fr','J''ai déjà dit à un proche que sa coupe était superbe alors que non.'),
('family','fr','Je me suis caché dans une salle de bain pour souffler pendant une fête de famille.'),
('family','fr','Je compte qui m''appelle en premier et je ne l''ai jamais dit à personne.'),
('family','fr','Je laisse courir une légende familiale sur moi parce qu''elle est plus flatteuse que la vérité.'),
('family','fr','J''ai un « beau » service de vaisselle que je n''ai jamais utilisé.'),
('family','fr','J''ai recyclé un projet scolaire et je l''ai rendu deux fois, à des années d''intervalle.'),
('family','fr','J''ai cherché en panique comment enlever une tache sur le tapis d''un proche.'),
('family','fr','Je fais semblant que mon téléphone est mort pour écourter les longs appels familiaux.'),
('family','fr','J''ai une nièce ou un neveu préféré et je lui apporte le meilleur cadeau.'),
('family','fr','Je demande encore à un parent de prendre mes rendez-vous chez le dentiste.'),
('family','fr','J''ai fini la dernière part de quelque chose et accusé un frère qui n''était même pas là.'),
('family','fr','J''ai un tiroir de câbles et je ne sais à quoi sert aucun d''eux.'),
('family','fr','J''ai ignoré l''appel d''un proche trois fois de suite puis écrit « désolé, débordé ! ».'),
('family','fr','Je sais exactement quelle lame de plancher grince et j''organise mes nuits en conséquence.'),
('family','fr','J''ai gardé exprès un livre de bibliothèque de ma ville d''enfance.'),
('family','fr','J''ai dit à tout le monde que j''avais cuisiné le repas. Le four a fait le plus gros.'),
('family','fr','J''ai un chargeur de secours caché pour que personne d''autre ne le prenne.'),
('family','fr','Je garde une rancune d''une partie de jeu de société de 2009 et je ne lâche rien.'),

-- kids (en)
('kids','en','I still line up my fries by size before eating them.'),
('kids','en','I have a comfort blanket and it lives in a drawer where guests will not see it.'),
('kids','en','I quote a kids'' movie at least once a day without meaning to.'),
('kids','en','I still avoid the cracks in the pavement, just in case.'),
('kids','en','I have a lucky number and I genuinely trust it with decisions.'),
('kids','en','I can still do a cartwheel and I show people at the worst times.'),
('kids','en','I kept a rock from a school trip and I still have it.'),
('kids','en','I secretly love the kids'' menu and order from it when I can.'),
('kids','en','I still make a wish at 11:11 every single time I catch it.'),
('kids','en','I once believed my toys moved at night and I still say goodnight to a plant.'),
('kids','en','I know all the words to a theme song from a show I have not watched in 20 years.'),
('kids','en','I still get a little scared going down the basement stairs.'),
('kids','en','I have a "spot" on the sofa and I get genuinely upset if someone takes it.'),
('kids','en','I still cannot sleep with a closet door open.'),
('kids','en','I hoard the good pens like a dragon and hide them from everyone.'),
('kids','en','I do a tiny victory dance when the microwave hits one second left.'),
('kids','en','I still think in gold stars — I gave myself three today.'),
('kids','en','I have never outgrown collecting shiny things I do not need.'),
('kids','en','I say "bless you" to myself when I sneeze alone.'),
('kids','en','I still cross my fingers behind my back and it still feels binding.'),
-- kids (fr)
('kids','fr','J''aligne encore mes frites par taille avant de les manger.'),
('kids','fr','J''ai un doudou et il vit dans un tiroir où les invités ne le verront pas.'),
('kids','fr','Je cite un film pour enfants au moins une fois par jour sans le vouloir.'),
('kids','fr','J''évite encore les fissures du trottoir, au cas où.'),
('kids','fr','J''ai un chiffre porte-bonheur et je lui confie vraiment mes décisions.'),
('kids','fr','Je sais encore faire la roue et je le montre aux pires moments.'),
('kids','fr','J''ai gardé un caillou d''une sortie scolaire et je l''ai encore.'),
('kids','fr','J''adore en secret le menu enfant et j''y commande dès que je peux.'),
('kids','fr','Je fais encore un vœu à 11 h 11 chaque fois que je le remarque.'),
('kids','fr','Je croyais que mes jouets bougeaient la nuit et je dis encore bonne nuit à une plante.'),
('kids','fr','Je connais toutes les paroles d''un générique d''une série que je n''ai pas vue depuis 20 ans.'),
('kids','fr','J''ai encore un peu peur en descendant l''escalier de la cave.'),
('kids','fr','J''ai une « place » sur le canapé et je me vexe vraiment si on la prend.'),
('kids','fr','Je n''arrive toujours pas à dormir avec une porte de placard ouverte.'),
('kids','fr','Je thésaurise les bons stylos comme un dragon et je les cache à tout le monde.'),
('kids','fr','Je fais une mini danse de la victoire quand le micro-ondes affiche une seconde.'),
('kids','fr','Je pense encore en étoiles d''or — je m''en suis donné trois aujourd''hui.'),
('kids','fr','Je n''ai jamais arrêté de collectionner des trucs brillants dont je n''ai pas besoin.'),
('kids','fr','Je me dis « à tes souhaits » à moi-même quand j''éternue seul.'),
('kids','fr','Je croise encore les doigts dans le dos et ça me semble toujours contraignant.'),

-- couples (en)
('couples','en','I have a note in my phone of things my partner said they liked, for gift emergencies.'),
('couples','en','I let my partner think they won an argument that I actually won.'),
('couples','en','I have rehearsed introducing someone as my partner before we were official.'),
('couples','en','I check my partner''s "on this day" memories more than my own.'),
('couples','en','I once picked a restaurant just because I knew an ex would never go there.'),
('couples','en','I keep the thermostat where I like it and blame "the settings".'),
('couples','en','I have pretended to be asleep to avoid a late-night deep talk.'),
('couples','en','I know my partner''s coffee order better than my own family''s names.'),
('couples','en','I have a folder of apartments we will "probably never" be able to afford.'),
('couples','en','I said I was fine with the movie choice and thought about it for days.'),
('couples','en','I have practised a proposal speech in the car with nobody in it.'),
('couples','en','I let my partner win at cards when they have had a bad day.'),
('couples','en','I have re-read our first messages more times than I would admit out loud.'),
('couples','en','I pretend I do not mind the dog on the bed. I mind. I let it happen anyway.'),
('couples','en','I have a running list of couples we are secretly competing with.'),
('couples','en','I said "I don''t care where we eat" and then vetoed four places.'),
('couples','en','I have googled my partner''s star sign compatibility with mine, twice.'),
('couples','en','I keep a spare gift in a cupboard in case I forget an occasion.'),
('couples','en','I have taken the bigger half and immediately felt guilty about it.'),
('couples','en','I told my partner the plant died from too much sun. I forgot to water it.'),
-- couples (fr)
('couples','fr','J''ai une note dans mon téléphone des trucs que mon/ma partenaire dit aimer, pour les cadeaux urgents.'),
('couples','fr','Je laisse mon/ma partenaire croire qu''il a gagné une dispute que j''ai gagnée.'),
('couples','fr','J''ai répété comment présenter quelqu''un comme mon/ma partenaire avant qu''on soit officiels.'),
('couples','fr','Je regarde les souvenirs « il y a un an » de mon/ma partenaire plus que les miens.'),
('couples','fr','J''ai choisi un resto juste parce qu''un ex n''y irait jamais.'),
('couples','fr','Je règle le thermostat comme je l''aime et j''accuse « les réglages ».'),
('couples','fr','J''ai fait semblant de dormir pour éviter une grande discussion tard le soir.'),
('couples','fr','Je connais la commande de café de mon/ma partenaire mieux que les prénoms de ma famille.'),
('couples','fr','J''ai un dossier d''appartements qu''on ne pourra « sans doute jamais » se payer.'),
('couples','fr','J''ai dit que le choix du film me convenait et j''y ai pensé pendant des jours.'),
('couples','fr','J''ai répété un discours de demande en mariage dans la voiture, seul.'),
('couples','fr','Je laisse mon/ma partenaire gagner aux cartes quand il a eu une mauvaise journée.'),
('couples','fr','J''ai relu nos premiers messages plus souvent que je ne l''avouerais à voix haute.'),
('couples','fr','Je fais semblant de ne pas être gêné par le chien sur le lit. Ça me gêne. Je laisse faire.'),
('couples','fr','J''ai une liste des couples avec qui on est secrètement en compétition.'),
('couples','fr','J''ai dit « je m''en fiche où on mange » puis j''ai refusé quatre endroits.'),
('couples','fr','J''ai cherché la compatibilité de nos signes astro, deux fois.'),
('couples','fr','Je garde un cadeau de secours dans un placard au cas où j''oublierais une occasion.'),
('couples','fr','J''ai pris la plus grosse moitié et j''ai culpabilisé aussitôt.'),
('couples','fr','J''ai dit que la plante est morte à cause du soleil. J''ai oublié de l''arroser.'),

-- girls_night (en)
('girls_night','en','I have re-recorded a voice note four times to sound more relaxed.'),
('girls_night','en','I own three of the same black top because I panic that they will stop making it.'),
('girls_night','en','I have zoomed in on a photo to check if someone was wearing my perfume.'),
('girls_night','en','I have a spreadsheet for a holiday I have not booked and may never take.'),
('girls_night','en','I have practised a "surprised" face in the mirror for a party I planned.'),
('girls_night','en','I keep an emergency outfit in my car and I have used it more than once.'),
('girls_night','en','I have left a group chat and rejoined so it would move to the top for someone.'),
('girls_night','en','I have taken 60 photos to post one and deleted the other 59 with no mercy.'),
('girls_night','en','I follow three accounts purely to feel superior on a bad day.'),
('girls_night','en','I have said "we should do this more often" and meant "not for a while".'),
('girls_night','en','I keep a list on my phone of comebacks I thought of in the shower.'),
('girls_night','en','I have booked a class, paid for it, and never once gone.'),
('girls_night','en','I match my nail colour to the season and I judge people who do not.'),
('girls_night','en','I have pretended a text "just came through" to leave a conversation.'),
('girls_night','en','I know my "angles" and I will reposition an entire group photo to get them.'),
('girls_night','en','I have a burner playlist for crying that I will take to my grave.'),
('girls_night','en','I have unfollowed and refollowed someone to reset the algorithm on purpose.'),
('girls_night','en','I have said an outfit was "so you" when I meant "please do not".'),
('girls_night','en','I keep every "you up?" text as evidence and I have never used it.'),
('girls_night','en','I have rehearsed a story so it lands better the third time I tell it tonight.'),
-- girls_night (fr)
('girls_night','fr','J''ai réenregistré un vocal quatre fois pour sembler plus détendue.'),
('girls_night','fr','J''ai trois fois le même haut noir parce que j''ai peur qu''ils arrêtent de le faire.'),
('girls_night','fr','J''ai zoomé sur une photo pour voir si quelqu''un portait mon parfum.'),
('girls_night','fr','J''ai un tableur pour des vacances que je n''ai pas réservées et ne prendrai peut-être jamais.'),
('girls_night','fr','J''ai répété une tête « surprise » dans le miroir pour une fête que j''avais organisée.'),
('girls_night','fr','Je garde une tenue de secours dans ma voiture et je m''en suis servie plus d''une fois.'),
('girls_night','fr','J''ai quitté une conversation de groupe puis je l''ai rejointe pour qu''elle remonte pour quelqu''un.'),
('girls_night','fr','J''ai pris 60 photos pour en publier une et supprimé les 59 autres sans pitié.'),
('girls_night','fr','Je suis trois comptes uniquement pour me sentir supérieure les mauvais jours.'),
('girls_night','fr','J''ai dit « il faut refaire ça plus souvent » en pensant « pas avant longtemps ».'),
('girls_night','fr','Je garde une liste dans mon téléphone des répliques que j''ai trouvées sous la douche.'),
('girls_night','fr','J''ai réservé un cours, payé, et je n''y suis jamais allée.'),
('girls_night','fr','J''assortis la couleur de mes ongles à la saison et je juge celles qui ne le font pas.'),
('girls_night','fr','J''ai fait semblant qu''un message « venait d''arriver » pour quitter une conversation.'),
('girls_night','fr','Je connais mes « angles » et je replace toute une photo de groupe pour les avoir.'),
('girls_night','fr','J''ai une playlist secrète pour pleurer que j''emporterai dans la tombe.'),
('girls_night','fr','Je me suis désabonnée et réabonnée de quelqu''un pour réinitialiser l''algorithme exprès.'),
('girls_night','fr','J''ai dit qu''une tenue était « tellement toi » en pensant « surtout pas ».'),
('girls_night','fr','Je garde chaque message « tu dors ? » comme preuve et je ne m''en suis jamais servie.'),
('girls_night','fr','J''ai répété une histoire pour qu''elle marche mieux la troisième fois ce soir.'),

-- guys_night (en)
('guys_night','en','I have nodded along to a plan I did not hear a single word of.'),
('guys_night','en','I have a tab open right now for something I will never buy.'),
('guys_night','en','I lost the group''s money on a "sure thing" and rounded it down when I told them.'),
('guys_night','en','I have watched a 40-minute video on a hobby I will start "next month".'),
('guys_night','en','I still have not read the book I have recommended to four people.'),
('guys_night','en','I have said "I''ll fix it this weekend" about the same shelf for a year.'),
('guys_night','en','I have practised a handshake so it would feel natural.'),
('guys_night','en','I keep a "one day" list of trips and I have not booked one of them.'),
('guys_night','en','I have googled a fact mid-argument and then pretended I already knew it.'),
('guys_night','en','I have a drawer of "important" receipts I will never look at again.'),
('guys_night','en','I have said the gym was "packed" when I turned around in the car park.'),
('guys_night','en','I have re-told a story with myself as the hero when I mostly just watched.'),
('guys_night','en','I have a playlist called "focus" that I have never once focused to.'),
('guys_night','en','I say "I only had a couple" and it is never a couple.'),
('guys_night','en','I have kept a broken thing for two years in case I "get around to it".'),
('guys_night','en','I have agreed to help someone move and immediately started planning an excuse.'),
('guys_night','en','I know the offside rule and I still argue it wrong on purpose to wind people up.'),
('guys_night','en','I have a "spare" phone charger at three friends'' houses and take theirs.'),
('guys_night','en','I have said "traffic was mad" when I left the house 15 minutes late.'),
('guys_night','en','I have watched a tutorial twice and still handed the job to someone else.'),
-- guys_night (fr)
('guys_night','fr','J''ai hoché la tête devant un plan dont je n''ai pas entendu un seul mot.'),
('guys_night','fr','J''ai un onglet ouvert là, maintenant, pour un truc que je n''achèterai jamais.'),
('guys_night','fr','J''ai perdu l''argent du groupe sur un « pari sûr » et j''ai arrondi vers le bas en le disant.'),
('guys_night','fr','J''ai regardé une vidéo de 40 minutes sur un loisir que je commencerai « le mois prochain ».'),
('guys_night','fr','Je n''ai toujours pas lu le livre que j''ai conseillé à quatre personnes.'),
('guys_night','fr','Je dis « je répare ça ce week-end » à propos de la même étagère depuis un an.'),
('guys_night','fr','J''ai répété une poignée de main pour qu''elle paraisse naturelle.'),
('guys_night','fr','J''ai une liste « un jour » de voyages et je n''en ai réservé aucun.'),
('guys_night','fr','J''ai cherché un fait en pleine dispute puis fait semblant de le savoir déjà.'),
('guys_night','fr','J''ai un tiroir de reçus « importants » que je ne regarderai plus jamais.'),
('guys_night','fr','J''ai dit que la salle de sport était « bondée » alors que j''ai fait demi-tour au parking.'),
('guys_night','fr','J''ai raconté une histoire en me mettant en héros alors que j''ai surtout regardé.'),
('guys_night','fr','J''ai une playlist « concentration » sur laquelle je ne me suis jamais concentré.'),
('guys_night','fr','Je dis « j''en ai pris deux ou trois » et ce n''est jamais deux ou trois.'),
('guys_night','fr','J''ai gardé un truc cassé pendant deux ans au cas où je « m''y mettrais ».'),
('guys_night','fr','J''ai accepté d''aider quelqu''un à déménager et j''ai aussitôt cherché une excuse.'),
('guys_night','fr','Je connais la règle du hors-jeu et je la défends mal exprès pour agacer les gens.'),
('guys_night','fr','J''ai un chargeur « de secours » chez trois amis et je prends le leur.'),
('guys_night','fr','J''ai dit « il y avait un trafic de fou » alors que je suis parti 15 minutes en retard.'),
('guys_night','fr','J''ai regardé un tuto deux fois et j''ai quand même confié le boulot à un autre.'),

-- work_party (en)
('work_party','en','I have said "as per my last email" while feeling powerful.'),
('work_party','en','I have joined a call two minutes late on purpose so I miss the small talk.'),
('work_party','en','I have a doc of things I would say if I ever quit dramatically.'),
('work_party','en','I have nodded in a meeting and then messaged a colleague "what did we agree?".'),
('work_party','en','I keep a "wins" folder and I have opened it on very bad afternoons.'),
('work_party','en','I have scheduled an email for 7am to look like an early starter.'),
('work_party','en','I have said "let''s take this offline" to end a conversation forever.'),
('work_party','en','I have muted myself to eat crisps during an all-hands.'),
('work_party','en','I have used "circling back" three times about a thing I hope everyone forgets.'),
('work_party','en','I have practised my "any questions?" pause so it looks confident.'),
('work_party','en','I have blamed a calendar glitch for a meeting I chose not to attend.'),
('work_party','en','I have a work persona and she is a lot more patient than I am.'),
('work_party','en','I have said "quick question" and then talked for eleven minutes.'),
('work_party','en','I have kept my camera off to eat lunch and "take notes".'),
('work_party','en','I have applied a "reply all" rule to my inbox out of pure spite.'),
('work_party','en','I have said "great catch" about something I should have caught myself.'),
('work_party','en','I have a folder called "misc" that is where projects go to disappear.'),
('work_party','en','I have googled a colleague''s job title to work out if I should be annoyed.'),
('work_party','en','I have said "I''m flexible" in a planning meeting and meant "I have opinions".'),
('work_party','en','I have finished a task early and sat on it so it did not look easy.'),
-- work_party (fr)
('work_party','fr','J''ai écrit « comme indiqué dans mon dernier courriel » en me sentant puissant.'),
('work_party','fr','J''arrive deux minutes en retard aux appels exprès pour éviter le bavardage.'),
('work_party','fr','J''ai un document de ce que je dirais si je démissionnais un jour avec fracas.'),
('work_party','fr','J''ai hoché la tête en réunion puis écrit à un collègue « on a décidé quoi ? ».'),
('work_party','fr','Je garde un dossier « réussites » et je l''ai ouvert lors de très mauvais après-midis.'),
('work_party','fr','J''ai programmé un courriel à 7 h pour avoir l''air matinal.'),
('work_party','fr','J''ai dit « on en reparle en privé » pour clore une conversation à jamais.'),
('work_party','fr','J''ai coupé mon micro pour manger des chips pendant une réunion générale.'),
('work_party','fr','J''ai dit « je reviens vers vous » trois fois sur un sujet que j''espère voir oublié.'),
('work_party','fr','J''ai répété ma pause « des questions ? » pour avoir l''air sûr de moi.'),
('work_party','fr','J''ai accusé un bug d''agenda pour une réunion que j''avais choisi de sécher.'),
('work_party','fr','J''ai une version pro de moi et elle est bien plus patiente que moi.'),
('work_party','fr','J''ai dit « petite question » puis j''ai parlé onze minutes.'),
('work_party','fr','J''ai gardé ma caméra éteinte pour déjeuner et « prendre des notes ».'),
('work_party','fr','J''ai mis une règle « répondre à tous » dans ma boîte par pure rancune.'),
('work_party','fr','J''ai dit « bien vu » à propos d''un truc que j''aurais dû voir moi-même.'),
('work_party','fr','J''ai un dossier « divers » où les projets vont disparaître.'),
('work_party','fr','J''ai cherché l''intitulé de poste d''un collègue pour savoir si je devais être vexé.'),
('work_party','fr','J''ai dit « je suis flexible » en réunion en pensant « j''ai des avis ».'),
('work_party','fr','J''ai fini une tâche en avance et je l''ai gardée pour ne pas avoir l''air que c''était facile.'),

-- awkward (en)
('awkward','en','I have said "you too" to "welcome to the store".'),
('awkward','en','I have held a door for so long that the person had to jog.'),
('awkward','en','I have laughed at a funeral because someone''s phone played a joke ringtone.'),
('awkward','en','I have gone in for a handshake and a hug at the same time and got neither.'),
('awkward','en','I have said "hi" to someone twice in one hour and panicked the second time.'),
('awkward','en','I have replied to a work email with a kiss at the end and watched it send.'),
('awkward','en','I have called my partner by a pet''s name in front of their parents.'),
('awkward','en','I have waved goodbye and then realised we were walking the same direction.'),
('awkward','en','I have pretended to take a call to avoid a chugger on the street.'),
('awkward','en','I have said "happy birthday" to the wrong twin, confidently.'),
('awkward','en','I have tripped on flat ground and then pretended to be jogging.'),
('awkward','en','I have thanked a bus driver who could not possibly hear me.'),
('awkward','en','I have finished a video call and kept talking to the black screen.'),
('awkward','en','I have said "see you later" to a stranger and then we got the same lift.'),
('awkward','en','I have autocorrected someone''s name to a fruit and hit send.'),
('awkward','en','I have clapped at the end of a film in an almost-empty cinema.'),
('awkward','en','I have said "no worries" to an apology for stepping on my foot, twice, hard.'),
('awkward','en','I have knocked on a door, panicked, and walked away before it opened.'),
('awkward','en','I have introduced my friend with the wrong job for two years.'),
('awkward','en','I have said "you as well" when a dentist told me to open wide.'),
-- awkward (fr)
('awkward','fr','J''ai répondu « vous aussi » à « bienvenue dans le magasin ».'),
('awkward','fr','J''ai tenu une porte si longtemps que la personne a dû courir.'),
('awkward','fr','J''ai ri à un enterrement parce que le téléphone de quelqu''un a joué une sonnerie comique.'),
('awkward','fr','J''ai tenté une poignée de main et une accolade en même temps et je n''ai eu ni l''une ni l''autre.'),
('awkward','fr','J''ai dit « bonjour » à quelqu''un deux fois en une heure et paniqué la deuxième.'),
('awkward','fr','J''ai répondu à un courriel de travail avec un bisou à la fin et je l''ai regardé partir.'),
('awkward','fr','J''ai appelé mon/ma partenaire par le nom d''un animal devant ses parents.'),
('awkward','fr','J''ai fait au revoir puis réalisé qu''on marchait dans la même direction.'),
('awkward','fr','J''ai fait semblant de répondre à un appel pour éviter un rabatteur dans la rue.'),
('awkward','fr','J''ai souhaité « joyeux anniversaire » au mauvais jumeau, avec assurance.'),
('awkward','fr','J''ai trébuché sur du plat puis j''ai fait semblant de faire du jogging.'),
('awkward','fr','J''ai remercié un chauffeur de bus qui ne pouvait absolument pas m''entendre.'),
('awkward','fr','J''ai terminé un appel vidéo et j''ai continué à parler à l''écran noir.'),
('awkward','fr','J''ai dit « à plus tard » à un inconnu, puis on a pris le même ascenseur.'),
('awkward','fr','J''ai laissé le correcteur changer le prénom de quelqu''un en fruit et j''ai envoyé.'),
('awkward','fr','J''ai applaudi à la fin d''un film dans un cinéma presque vide.'),
('awkward','fr','J''ai dit « pas de souci » à des excuses pour m''avoir marché sur le pied, deux fois, fort.'),
('awkward','fr','J''ai frappé à une porte, paniqué, et je suis parti avant qu''elle s''ouvre.'),
('awkward','fr','J''ai présenté mon ami avec le mauvais métier pendant deux ans.'),
('awkward','fr','J''ai dit « vous aussi » quand un dentiste m''a dit d''ouvrir grand.'),

-- wholesome (en)
('wholesome','en','I keep a jar of good things that happened and read it when the week is heavy.'),
('wholesome','en','I have a favourite tree on my walk and I say hello to it.'),
('wholesome','en','I learned a friend''s coffee order by heart as a surprise.'),
('wholesome','en','I still have the first drawing a kid in my life ever gave me, framed.'),
('wholesome','en','I leave the good parking spot for whoever comes after me.'),
('wholesome','en','I have a playlist that is just songs my grandparents loved.'),
('wholesome','en','I write tiny encouraging notes and hide them in library books.'),
('wholesome','en','I keep an umbrella by the door that is only for lending out.'),
('wholesome','en','I have a "sunset" alarm so I do not miss a good one.'),
('wholesome','en','I still call my childhood best friend on their birthday, every year.'),
('wholesome','en','I keep every ticket stub from a day that felt perfect.'),
('wholesome','en','I have a "just because" gift drawer for friends who have had a rough week.'),
('wholesome','en','I water my neighbour''s plants better than my own and never mention it.'),
('wholesome','en','I have re-read the same three books so many times the covers gave up.'),
('wholesome','en','I keep the birthday candles from a cake that made someone cry happy tears.'),
('wholesome','en','I say "drive safe" and I genuinely worry until I hear back.'),
('wholesome','en','I have a folder of memes I am saving for specific friends on bad days.'),
('wholesome','en','I still use a bookmark a stranger gave me on a train ten years ago.'),
('wholesome','en','I learned to make one dish just so I could bring it to people who are sad.'),
('wholesome','en','I keep a spare phone charger for guests and I am weirdly proud of it.'),
-- wholesome (fr)
('wholesome','fr','Je garde un bocal de bonnes choses arrivées et je le lis quand la semaine est lourde.'),
('wholesome','fr','J''ai un arbre préféré sur mon trajet à pied et je le salue.'),
('wholesome','fr','J''ai appris par cœur la commande de café d''un ami pour lui faire la surprise.'),
('wholesome','fr','J''ai encore, encadré, le premier dessin qu''un enfant de ma vie m''a offert.'),
('wholesome','fr','Je laisse la bonne place de parking à celui qui viendra après moi.'),
('wholesome','fr','J''ai une playlist qui n''est que des chansons qu''adoraient mes grands-parents.'),
('wholesome','fr','J''écris de petits mots d''encouragement et je les cache dans des livres de bibliothèque.'),
('wholesome','fr','Je garde un parapluie près de la porte, uniquement pour le prêter.'),
('wholesome','fr','J''ai une alarme « coucher de soleil » pour ne pas en rater un beau.'),
('wholesome','fr','J''appelle encore mon meilleur ami d''enfance le jour de son anniversaire, chaque année.'),
('wholesome','fr','Je garde chaque billet d''une journée qui semblait parfaite.'),
('wholesome','fr','J''ai un tiroir à cadeaux « sans raison » pour les amis qui ont eu une semaine dure.'),
('wholesome','fr','J''arrose les plantes de ma voisine mieux que les miennes et je ne le dis jamais.'),
('wholesome','fr','J''ai relu les mêmes trois livres si souvent que les couvertures ont lâché.'),
('wholesome','fr','Je garde les bougies d''un gâteau qui a fait pleurer quelqu''un de joie.'),
('wholesome','fr','Je dis « conduis prudemment » et je m''inquiète vraiment jusqu''à la réponse.'),
('wholesome','fr','J''ai un dossier de mèmes que je garde pour des amis précis les mauvais jours.'),
('wholesome','fr','J''utilise encore un marque-page qu''un inconnu m''a donné dans un train il y a dix ans.'),
('wholesome','fr','J''ai appris à faire un plat juste pour l''apporter aux gens tristes.'),
('wholesome','fr','Je garde un chargeur de secours pour les invités et j''en suis bizarrement fier.'),

-- dark (en)
('dark','en','I have let a plant die on purpose because it reminded me of someone.'),
('dark','en','I have kept reading a chat after being told the person had blocked me elsewhere.'),
('dark','en','I have practised what I would say at someone''s leaving party and enjoyed it too much.'),
('dark','en','I have said a friend''s secret out loud alone just to hear how it sounds.'),
('dark','en','I have declined an invite and then watched the whole night unfold online.'),
('dark','en','I have kept a gift from someone I no longer speak to and I still use it daily.'),
('dark','en','I have let a group think a mistake was a shared one when it was only mine.'),
('dark','en','I have a mental list of people I would not warn if I saw them about to trip.'),
('dark','en','I have re-read an old argument to make sure I was still right. I was not, fully.'),
('dark','en','I have said "we should catch up" to someone I would cross the road to avoid.'),
('dark','en','I have kept a screenshot for two years in case I ever need to end a friendship cleanly.'),
('dark','en','I have felt relieved when plans got cancelled by a small emergency that was not mine.'),
('dark','en','I have let someone apologise for a thing that was, on balance, mostly my fault.'),
('dark','en','I have a "do not resuscitate" list for group chats and I add to it quietly.'),
('dark','en','I have smiled through a compliment I knew was a dig and filed it away.'),
('dark','en','I have kept score in a friendship for so long that I forgot why I started.'),
('dark','en','I have unfollowed someone the day after they were kind to me, out of pettiness.'),
('dark','en','I have told a story about someone that was true but told to make them look worse.'),
('dark','en','I have wished a rival''s big day would go just slightly, forgettably wrong.'),
('dark','en','I have kept a spare key I was asked to return, and I know exactly where it is.'),
-- dark (fr)
('dark','fr','J''ai laissé une plante mourir exprès parce qu''elle me rappelait quelqu''un.'),
('dark','fr','J''ai continué à lire une conversation après avoir su que la personne m''avait bloqué ailleurs.'),
('dark','fr','J''ai répété ce que je dirais au pot de départ de quelqu''un et j''y ai pris trop de plaisir.'),
('dark','fr','J''ai dit le secret d''un ami à voix haute, seul, juste pour entendre comment ça sonne.'),
('dark','fr','J''ai décliné une invitation puis suivi toute la soirée en ligne.'),
('dark','fr','J''ai gardé un cadeau de quelqu''un à qui je ne parle plus et je m''en sers tous les jours.'),
('dark','fr','J''ai laissé un groupe croire qu''une erreur était collective alors qu''elle n''était que la mienne.'),
('dark','fr','J''ai une liste mentale de gens que je ne préviendrais pas si je les voyais sur le point de trébucher.'),
('dark','fr','J''ai relu une vieille dispute pour vérifier que j''avais raison. Pas totalement.'),
('dark','fr','J''ai dit « faut se revoir » à quelqu''un que je traverserais la rue pour éviter.'),
('dark','fr','J''ai gardé une capture d''écran pendant deux ans au cas où je devrais couper une amitié proprement.'),
('dark','fr','J''ai ressenti du soulagement quand des plans ont sauté à cause d''une petite urgence qui n''était pas la mienne.'),
('dark','fr','J''ai laissé quelqu''un s''excuser pour une chose qui était, tout compte fait, surtout ma faute.'),
('dark','fr','J''ai une liste « à ne pas ranimer » pour les conversations de groupe et je l''allonge en silence.'),
('dark','fr','J''ai souri à un compliment que je savais être une pique, et je l''ai classé.'),
('dark','fr','J''ai tenu les comptes dans une amitié si longtemps que j''ai oublié pourquoi j''avais commencé.'),
('dark','fr','Je me suis désabonné de quelqu''un le lendemain de sa gentillesse envers moi, par mesquinerie.'),
('dark','fr','J''ai raconté sur quelqu''un une histoire vraie mais tournée pour le faire mal paraître.'),
('dark','fr','J''ai souhaité que le grand jour d''un rival tourne juste un peu, discrètement, mal.'),
('dark','fr','J''ai gardé un double de clé qu''on m''avait demandé de rendre, et je sais exactement où il est.'),

-- spicy (en)
('spicy','en','I have kept a contact saved as a food item and everyone in this room knows one of theirs is fake too.'),
('spicy','en','I have left a party early to see someone I told my friends I was "so over".'),
('spicy','en','I have practised a text for 20 minutes and then sent "hey" with no punctuation.'),
('spicy','en','I have gone back through someone''s photos far enough to be a genuine risk.'),
('spicy','en','I have worn a specific outfit only because I knew one particular person would see it.'),
('spicy','en','I have said "I''m not looking for anything serious" and then reorganised my week around them.'),
('spicy','en','I have a "seen at 2am" habit I am not proud of.'),
('spicy','en','I have kept someone''s jumper through two moves and one relationship.'),
('spicy','en','I have rehearsed running into an ex so I would look unbothered.'),
('spicy','en','I have muted someone so I could keep watching without it being obvious.'),
('spicy','en','I have said "let''s just be friends" and then been weird about them having friends.'),
('spicy','en','I have re-downloaded an app for one specific person and deleted it in shame.'),
('spicy','en','I have picked a coffee shop purely for the chance of a run-in.'),
('spicy','en','I have kept a playlist a date made me and I still skip the same song they warned me about.'),
('spicy','en','I have replied to a story just to move myself up someone''s list.'),
('spicy','en','I have practised a "casual" leaning pose for when a certain person walks in.'),
('spicy','en','I have gone to an event I did not care about because of one name on the guest list.'),
('spicy','en','I have said "no rush" about a reply I checked my phone for every four minutes.'),
('spicy','en','I have kept a first-date receipt in a book like it was a boarding pass.'),
('spicy','en','I have deleted a text, retyped it word for word, and sent it anyway.'),
-- spicy (fr)
('spicy','fr','J''ai un contact enregistré sous un nom de plat et tout le monde ici sait qu''un des siens est faux aussi.'),
('spicy','fr','J''ai quitté une fête tôt pour voir quelqu''un dont j''avais dit à mes amis être « complètement passé à autre chose ».'),
('spicy','fr','J''ai répété un message pendant 20 minutes puis envoyé « salut » sans ponctuation.'),
('spicy','fr','J''ai remonté les photos de quelqu''un assez loin pour être un vrai risque.'),
('spicy','fr','J''ai porté une tenue précise uniquement parce qu''une personne en particulier la verrait.'),
('spicy','fr','J''ai dit « je ne cherche rien de sérieux » puis j''ai réorganisé ma semaine autour d''elle.'),
('spicy','fr','J''ai une habitude de « vu à 2 h du matin » dont je ne suis pas fier.'),
('spicy','fr','J''ai gardé le pull de quelqu''un à travers deux déménagements et une relation.'),
('spicy','fr','J''ai répété une rencontre fortuite avec un ex pour avoir l''air indifférent.'),
('spicy','fr','J''ai mis quelqu''un en sourdine pour continuer à regarder sans que ça se voie.'),
('spicy','fr','J''ai dit « restons juste amis » puis j''ai été bizarre qu''il ait des amis.'),
('spicy','fr','J''ai réinstallé une appli pour une personne précise et je l''ai supprimée de honte.'),
('spicy','fr','J''ai choisi un café uniquement pour la chance d''une rencontre.'),
('spicy','fr','J''ai gardé une playlist faite par un rendez-vous et je saute encore la chanson dont il m''avait prévenu.'),
('spicy','fr','J''ai répondu à une story juste pour remonter dans la liste de quelqu''un.'),
('spicy','fr','J''ai répété une pose « nonchalante » appuyée pour quand une certaine personne entre.'),
('spicy','fr','Je suis allé à un événement qui m''indifférait à cause d''un seul nom sur la liste.'),
('spicy','fr','J''ai dit « prends ton temps » pour une réponse que j''ai vérifiée toutes les quatre minutes.'),
('spicy','fr','J''ai gardé le reçu d''un premier rendez-vous dans un livre comme une carte d''embarquement.'),
('spicy','fr','J''ai supprimé un message, retapé mot pour mot, et envoyé quand même.')
on conflict do nothing;
