-- Starter content for public.secret_bank (item 21). Curated, bilingual, and
-- deliberately kept to a readable size — the decision was "~600-800 later,
-- expandable"; this is the first ~200 and the table is built to grow. Add more
-- with further `insert ... on conflict do nothing` migrations.
--
-- Categories: family, kids, couples, girls_night, guys_night, work_party,
-- awkward, wholesome, dark, spicy. The host picks one (or "mixed") when
-- creating a game; "mixed" draws from all of them.

insert into public.secret_bank (category, locale, text) values
-- family (en)
('family','en','I still phone a parent to ask how to cook basic meals.'),
('family','en','I have a favourite sibling and they know it.'),
('family','en','I once regifted a present back to the person who gave it to me.'),
('family','en','I lose board games on purpose against the youngest cousins.'),
('family','en','I have never finished a book my family told me to read.'),
('family','en','I read the family group chat every day and never reply.'),
('family','en','I broke a family heirloom and let the pet take the blame.'),
('family','en','I know a family recipe and refuse to share it.'),
('family','en','I still get money slipped to me by a relative.'),
('family','en','I skipped a family reunion by inventing a work trip.'),
-- family (fr)
('family','fr','J''appelle encore un parent pour savoir comment cuire des pâtes.'),
('family','fr','J''ai un frère ou une sœur préféré et il le sait.'),
('family','fr','J''ai déjà réoffert un cadeau à la personne qui me l''avait donné.'),
('family','fr','Je perds exprès aux jeux de société contre les plus jeunes cousins.'),
('family','fr','Je n''ai jamais fini un livre conseillé par ma famille.'),
('family','fr','Je lis le groupe familial chaque jour sans jamais répondre.'),
('family','fr','J''ai cassé un objet de famille et laissé l''animal porter le blâme.'),
('family','fr','Je connais une recette de famille et je refuse de la partager.'),
('family','fr','Un proche me glisse encore de l''argent en cachette.'),
('family','fr','J''ai raté une réunion de famille en inventant un voyage de travail.'),

-- kids (en)
('kids','en','I still sleep with a stuffed animal.'),
('kids','en','I have never watched a full football match on purpose.'),
('kids','en','I can name more cartoon characters than world capitals.'),
('kids','en','I once cried at an animated movie in the cinema this year.'),
('kids','en','I still know every word of a song from primary school.'),
('kids','en','I keep a tub of childhood toys I will never give away.'),
('kids','en','I invented an imaginary friend and still remember their name.'),
('kids','en','I was sent out of class more than once and my parents never knew.'),
('kids','en','I believed a wildly wrong fact until I was an adult.'),
('kids','en','I still do a secret handshake with a childhood friend.'),
-- kids (fr)
('kids','fr','Je dors encore avec une peluche.'),
('kids','fr','Je n''ai jamais regardé un match de foot en entier volontairement.'),
('kids','fr','Je connais plus de personnages de dessins animés que de capitales.'),
('kids','fr','J''ai pleuré devant un film d''animation au cinéma cette année.'),
('kids','fr','Je connais encore par cœur une chanson de l''école primaire.'),
('kids','fr','Je garde une caisse de jouets d''enfance que je ne donnerai jamais.'),
('kids','fr','J''avais un ami imaginaire et je me souviens encore de son nom.'),
('kids','fr','J''ai été mis à la porte de la classe et mes parents ne l''ont jamais su.'),
('kids','fr','J''ai cru à une info complètement fausse jusqu''à l''âge adulte.'),
('kids','fr','Je fais encore un check secret avec un ami d''enfance.'),

-- couples (en)
('couples','en','I have a folder of screenshots of things I want to be gifted.'),
('couples','en','I have googled my partner''s ex more than once.'),
('couples','en','I say I am five minutes away when I have not left yet.'),
('couples','en','I pretend to like a hobby just to spend time with someone.'),
('couples','en','I have a "type" and everyone in this room knows what it is.'),
('couples','en','I kept a gift from an ex and still use it.'),
('couples','en','I have practised an argument in the shower and still lost it.'),
('couples','en','I check my partner''s horoscope before mine.'),
('couples','en','I have re-read old messages from a crush this month.'),
('couples','en','I let someone win me over purely with good snacks.'),
-- couples (fr)
('couples','fr','J''ai un dossier de captures d''écran des choses que je veux qu''on m''offre.'),
('couples','fr','J''ai déjà cherché l''ex de mon/ma partenaire sur Google plus d''une fois.'),
('couples','fr','Je dis que je suis à cinq minutes alors que je ne suis pas parti.'),
('couples','fr','Je fais semblant d''aimer un loisir juste pour voir quelqu''un.'),
('couples','fr','J''ai un « genre » et tout le monde ici sait lequel.'),
('couples','fr','J''ai gardé un cadeau d''un ex et je m''en sers encore.'),
('couples','fr','J''ai répété une dispute sous la douche et je l''ai quand même perdue.'),
('couples','fr','Je lis l''horoscope de mon/ma partenaire avant le mien.'),
('couples','fr','J''ai relu de vieux messages d''un crush ce mois-ci.'),
('couples','fr','Quelqu''un m''a séduit uniquement avec de bons snacks.'),

-- girls_night (en)
('girls_night','en','I have left a party without telling anyone at least three times.'),
('girls_night','en','I have a burner social account just to watch people.'),
('girls_night','en','I have cried in a nightclub bathroom and come out fine.'),
('girls_night','en','I rehearse voice notes before I send them.'),
('girls_night','en','I have kept a dress with the tag on for over a year.'),
('girls_night','en','I have taken a photo of a stranger''s outfit for inspiration.'),
('girls_night','en','I have a group chat that exists only to discuss one other person.'),
('girls_night','en','I have booked a fake dinner to get out of plans.'),
('girls_night','en','I know my coffee order has become a personality trait.'),
('girls_night','en','I have followed someone for years and never liked a single post.'),
-- girls_night (fr)
('girls_night','fr','J''ai quitté une soirée sans prévenir personne au moins trois fois.'),
('girls_night','fr','J''ai un compte secret juste pour observer les gens.'),
('girls_night','fr','J''ai pleuré dans les toilettes d''une boîte et je suis ressortie très bien.'),
('girls_night','fr','Je répète mes messages vocaux avant de les envoyer.'),
('girls_night','fr','J''ai gardé une robe avec l''étiquette pendant plus d''un an.'),
('girls_night','fr','J''ai pris en photo la tenue d''une inconnue pour m''en inspirer.'),
('girls_night','fr','J''ai une conversation de groupe qui ne sert qu''à parler d''une seule personne.'),
('girls_night','fr','J''ai inventé un dîner pour annuler des plans.'),
('girls_night','fr','Je sais que ma commande de café est devenue un trait de personnalité.'),
('girls_night','fr','Je suis quelqu''un depuis des années sans jamais aimer une publication.'),

-- guys_night (en)
('guys_night','en','I have googled "is it normal that" more times than I will admit.'),
('guys_night','en','I lost a bet years ago and never paid up.'),
('guys_night','en','I have a fantasy team for a sport I do not actually watch.'),
('guys_night','en','I still quote a film nobody else in this room has seen.'),
('guys_night','en','I once took credit for a meal that was delivered.'),
('guys_night','en','I have pretended to know a band to seem cooler.'),
('guys_night','en','I keep a spreadsheet for something that does not need one.'),
('guys_night','en','I have practised a "casual" photo pose in the mirror.'),
('guys_night','en','I have told the same story to the same person twice this month.'),
('guys_night','en','I own gym clothes I have only ever worn to brunch.'),
-- guys_night (fr)
('guys_night','fr','J''ai tapé « est-ce normal que » plus de fois que je ne l''avouerai.'),
('guys_night','fr','J''ai perdu un pari il y a des années et je n''ai jamais payé.'),
('guys_night','fr','J''ai une équipe fantasy pour un sport que je ne regarde même pas.'),
('guys_night','fr','Je cite encore un film que personne ici n''a vu.'),
('guys_night','fr','Je me suis attribué le mérite d''un repas qui était livré.'),
('guys_night','fr','J''ai fait semblant de connaître un groupe pour paraître plus cool.'),
('guys_night','fr','Je tiens un tableur pour un truc qui n''en a pas besoin.'),
('guys_night','fr','J''ai répété une pose « naturelle » devant le miroir.'),
('guys_night','fr','J''ai raconté la même histoire à la même personne deux fois ce mois-ci.'),
('guys_night','fr','J''ai des vêtements de sport que je n''ai portés qu''au brunch.'),

-- work_party (en)
('work_party','en','I have muted a meeting to finish my lunch.'),
('work_party','en','I have said "let me circle back" with no intention of circling back.'),
('work_party','en','I once fixed a bug by turning it off and on and took full credit.'),
('work_party','en','I have a document titled "notes" that is just complaints.'),
('work_party','en','I have applied to a job just to see if I would get an interview.'),
('work_party','en','I keep my status green while making tea for 20 minutes.'),
('work_party','en','I have forgotten a colleague''s name for over a year.'),
('work_party','en','I have presented a slide I did not read until that moment.'),
('work_party','en','I laugh at jokes in meetings I did not hear.'),
('work_party','en','I have a folder of emails I will "deal with later" from last spring.'),
-- work_party (fr)
('work_party','fr','J''ai coupé mon micro en réunion pour finir mon repas.'),
('work_party','fr','J''ai dit « je reviens vers toi » sans aucune intention de revenir.'),
('work_party','fr','J''ai réglé un bug en redémarrant et je me suis attribué tout le mérite.'),
('work_party','fr','J''ai un document intitulé « notes » qui n''est que des plaintes.'),
('work_party','fr','J''ai postulé à un poste juste pour voir si j''aurais un entretien.'),
('work_party','fr','Je garde mon statut en vert pendant que je fais un thé de 20 minutes.'),
('work_party','fr','J''ai oublié le prénom d''un collègue depuis plus d''un an.'),
('work_party','fr','J''ai présenté une diapo que je découvrais à cet instant.'),
('work_party','fr','Je ris à des blagues en réunion que je n''ai pas entendues.'),
('work_party','fr','J''ai un dossier d''e-mails « à traiter plus tard » depuis le printemps dernier.'),

-- awkward (en)
('awkward','en','I have waved back at someone who was waving at the person behind me.'),
('awkward','en','I have called a teacher "mum" or "dad" out loud.'),
('awkward','en','I once said "you too" when a waiter said "enjoy your meal".'),
('awkward','en','I have pushed a pull door in front of a queue of people.'),
('awkward','en','I have left a shop because the assistant was too helpful.'),
('awkward','en','I have practised saying my own name after forgetting how it sounds.'),
('awkward','en','I have hidden in an aisle to avoid saying hi to someone.'),
('awkward','en','I have replied "happy birthday" to a message that was not that.'),
('awkward','en','I once clapped when the plane landed and no one joined.'),
('awkward','en','I have introduced someone using completely the wrong name.'),
-- awkward (fr)
('awkward','fr','J''ai fait signe à quelqu''un qui saluait la personne derrière moi.'),
('awkward','fr','J''ai appelé un prof « maman » ou « papa » à voix haute.'),
('awkward','fr','J''ai répondu « vous aussi » à un serveur qui me souhaitait bon appétit.'),
('awkward','fr','J''ai poussé une porte « tirez » devant une file de gens.'),
('awkward','fr','J''ai quitté un magasin parce que le vendeur était trop serviable.'),
('awkward','fr','J''ai répété mon propre prénom après avoir oublié comment il sonnait.'),
('awkward','fr','Je me suis caché dans un rayon pour éviter de dire bonjour à quelqu''un.'),
('awkward','fr','J''ai répondu « joyeux anniversaire » à un message qui n''en était pas un.'),
('awkward','fr','J''ai applaudi à l''atterrissage de l''avion et personne n''a suivi.'),
('awkward','fr','J''ai présenté quelqu''un avec un prénom totalement faux.'),

-- wholesome (en)
('wholesome','en','I still keep every birthday card anyone has ever given me.'),
('wholesome','en','I talk to bees in the garden and wish them a good day.'),
('wholesome','en','I have a playlist named after a friend for when I miss them.'),
('wholesome','en','I learned a card trick just to show one specific kid.'),
('wholesome','en','I leave the porch light on for a neighbour who works late.'),
('wholesome','en','I name every plant I own.'),
('wholesome','en','I have re-watched the same comfort show more than ten times.'),
('wholesome','en','I keep a note on my phone of nice things strangers have said to me.'),
('wholesome','en','I bake for people when I do not know what else to say.'),
('wholesome','en','I still use a mug a friend made me even though it leaks.'),
-- wholesome (fr)
('wholesome','fr','Je garde encore toutes les cartes d''anniversaire qu''on m''a offertes.'),
('wholesome','fr','Je parle aux abeilles dans le jardin et je leur souhaite une bonne journée.'),
('wholesome','fr','J''ai une playlist au nom d''un ami pour quand il me manque.'),
('wholesome','fr','J''ai appris un tour de cartes juste pour le montrer à un enfant en particulier.'),
('wholesome','fr','Je laisse la lumière du perron allumée pour un voisin qui rentre tard.'),
('wholesome','fr','Je donne un prénom à chacune de mes plantes.'),
('wholesome','fr','J''ai revu plus de dix fois la même série doudou.'),
('wholesome','fr','Je garde une note dans mon téléphone des gentillesses que des inconnus m''ont dites.'),
('wholesome','fr','Je fais des gâteaux pour les gens quand je ne sais pas quoi dire d''autre.'),
('wholesome','fr','J''utilise encore une tasse qu''un ami a faite même si elle fuit.'),

-- dark (en)
('dark','en','I have kept a secret for a friend that I probably should not have.'),
('dark','en','I have let someone believe a lie because the truth was more work.'),
('dark','en','I once quit something the day before a big deadline and never explained.'),
('dark','en','I have a grudge from school that I have never let go of.'),
('dark','en','I have read a message and decided to pretend I never saw it.'),
('dark','en','I have deleted a photo of a whole trip because I looked bad in it.'),
('dark','en','I once let a team take the blame for a mistake that was mine.'),
('dark','en','I have unfollowed someone and then acted surprised when they noticed.'),
('dark','en','I have said I was "so sick" when I just needed a day alone.'),
('dark','en','I keep a mental list of people who wronged me and it is alphabetised.'),
-- dark (fr)
('dark','fr','J''ai gardé pour un ami un secret que je n''aurais sans doute pas dû garder.'),
('dark','fr','J''ai laissé quelqu''un croire un mensonge parce que la vérité était trop compliquée.'),
('dark','fr','J''ai tout abandonné la veille d''une grande échéance sans jamais m''expliquer.'),
('dark','fr','J''ai une rancune d''école que je n''ai jamais lâchée.'),
('dark','fr','J''ai lu un message et décidé de faire comme si je ne l''avais jamais vu.'),
('dark','fr','J''ai supprimé les photos d''un voyage entier parce que j''étais mal dessus.'),
('dark','fr','J''ai laissé une équipe porter le blâme d''une erreur qui était la mienne.'),
('dark','fr','Je me suis désabonné de quelqu''un puis j''ai joué la surprise quand il l''a remarqué.'),
('dark','fr','J''ai dit que j''étais « super malade » alors qu''il me fallait juste une journée seul.'),
('dark','fr','Je tiens une liste mentale des gens qui m''ont fait du tort, classée par ordre alphabétique.'),

-- spicy (en)
('spicy','en','I have flirted my way out of a fine at least once.'),
('spicy','en','I have a "do not text" contact I still text.'),
('spicy','en','I once left a date to go on a better date the same night.'),
('spicy','en','I have kept someone''s hoodie longer than I kept the relationship.'),
('spicy','en','I have used a dating app in a city I was only visiting for a day.'),
('spicy','en','I have rehearsed a breakup speech and then not used it.'),
('spicy','en','Someone in my phone is saved under a fake name for a reason.'),
('spicy','en','I have gone back to an ex purely out of boredom.'),
('spicy','en','I have lied about my "number" in both directions depending on the room.'),
('spicy','en','I have a crush on someone I have never actually spoken to.'),
-- spicy (fr)
('spicy','fr','J''ai déjà évité une amende en jouant du charme au moins une fois.'),
('spicy','fr','J''ai un contact « ne pas écrire » à qui j''écris encore.'),
('spicy','fr','J''ai quitté un rendez-vous pour un meilleur rendez-vous le même soir.'),
('spicy','fr','J''ai gardé le sweat de quelqu''un plus longtemps que la relation.'),
('spicy','fr','J''ai utilisé une appli de rencontres dans une ville où je passais un seul jour.'),
('spicy','fr','J''ai répété un discours de rupture puis je ne l''ai pas utilisé.'),
('spicy','fr','Quelqu''un dans mon téléphone est enregistré sous un faux nom, et pour cause.'),
('spicy','fr','Je suis retourné avec un ex uniquement par ennui.'),
('spicy','fr','J''ai menti sur mon « nombre » dans les deux sens selon les gens présents.'),
('spicy','fr','J''ai un crush sur quelqu''un à qui je n''ai jamais vraiment parlé.')
on conflict do nothing;
